name: Playwright Tests
on: 
  # push:
  #   branches: [ main, master ]
  schedule:
    - cron: '*/30 * * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      # if: failure()
      if: success()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          LE ISCRIZIONI AL CORSO DI NATURALIZAZIONE SONO APERTE! https://www.ifc.ti.ch/corsi/tutti-i-corsi/dettaglio/2324asoc0140001_corsi-di-formazione-alla-cittadinanza
